from __future__ import annotations

from enum import StrEnum
from typing import NewType

SessionId = NewType("SessionId", str)
TurnId = NewType("TurnId", str)


class TimelineEventName(StrEnum):
    WAKE = "WAKE"
    LISTEN_START = "LISTEN_START"
    VAD_START = "VAD_START"
    VAD_END = "VAD_END"
    ASR_CONNECT_START = "ASR_CONNECT_START"
    ASR_READY = "ASR_READY"
    FIRST_PCM_SENT = "FIRST_PCM_SENT"
    ASR_FINAL = "ASR_FINAL"
    RESOLVER_START = "RESOLVER_START"
    RESOLVER_END = "RESOLVER_END"
    INTENT_START = "INTENT_START"
    INTENT_END = "INTENT_END"
    TOOL_START = "TOOL_START"
    TOOL_END = "TOOL_END"
    LLM_START = "LLM_START"
    LLM_FIRST_TOKEN = "LLM_FIRST_TOKEN"
    LLM_END = "LLM_END"
    TTS_START = "TTS_START"
    TTS_FIRST_AUDIO = "TTS_FIRST_AUDIO"
    DEVICE_FIRST_AUDIO = "DEVICE_FIRST_AUDIO"
    TURN_END = "TURN_END"
    TURN_CANCEL = "TURN_CANCEL"
    HELLO = "HELLO"
    ASR_RECONNECT = "ASR_RECONNECT"
    IDLE_TIMEOUT = "IDLE_TIMEOUT"
    FALLBACK_V1 = "FALLBACK_V1"


class PcmDisposition(StrEnum):
    SENT = "SENT"
    DISCARDED = "DISCARDED"
    PENDING = "PENDING"


class DiscardReason(StrEnum):
    WAKE_ISOLATION = "WAKE_ISOLATION"
    WAKE_SOURCE = "WAKE_SOURCE"
    CONVERSATION_CLOSED = "CONVERSATION_CLOSED"
    ASR_NOT_READY = "ASR_NOT_READY"
    DUPLICATE_FRAME = "DUPLICATE_FRAME"
    STALE_EPOCH = "STALE_EPOCH"
    STALE_BUFFER = "STALE_BUFFER"
    SESSION_RESET = "SESSION_RESET"
    TURN_CANCELLED = "TURN_CANCELLED"
    ASR_CONNECT_TIMEOUT = "ASR_CONNECT_TIMEOUT"
    ENGINE_NOT_PRIMARY = "ENGINE_NOT_PRIMARY"
    SHADOW_OBSERVE_ONLY = "SHADOW_OBSERVE_ONLY"
    AFTER_VAD_END = "AFTER_VAD_END"
    IDLE_TIMEOUT = "IDLE_TIMEOUT"


class TtsPlaybackState(StrEnum):
    IDLE = "IDLE"
    GENERATING = "GENERATING"
    QUEUED = "QUEUED"
    SENDING = "SENDING"
    PLAYING = "PLAYING"
    DRAINING = "DRAINING"
    INTERRUPTED = "INTERRUPTED"


class LocationStatus(StrEnum):
    KNOWN = "KNOWN"
    LOCATION_UNKNOWN = "LOCATION_UNKNOWN"
    REJECTED_FALLBACK = "REJECTED_FALLBACK"


class IntentName(StrEnum):
    CHAT = "CHAT"
    MUSIC = "MUSIC"
    WEATHER = "WEATHER"
    LOCATION = "LOCATION"
    GOODBYE = "GOODBYE"
    UNKNOWN = "UNKNOWN"
